name: Django Telex APM CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  linting:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort bandit pytest pytest-cov

      - name: Run Flake8 (Linting)
        run: flake8 --max-line-length=88

      - name: Run Code Quality Check
        run: flake8 --exclude=migrations .

      - name: Run Black (Formatting Check)
        run: black --check .

      - name: Run isort (Import Sorting Check)
        run: isort . --check-only

      - name: Run Bandit (Security Checks)
        run: bandit -r .

  testing:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: linting

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Code Quality Checks
        run: bash quality_check.sh

      - name: Run Pytest with Coverage
        run: pytest --cov=djangotelex --cov-report=xml

      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
